# Application-wide configs
routes:
  publicPrefix: "/public"
  protectedPrefix: "/protected"
  webhookPrefix: "/webhook"

cors:
  origin: "${CLIENT_URL}" # '${CLIENT_URL}' is replaced with process.env.CLIENT_URL
  methods: "GET,HEAD,PUT,PATCH,POST,DELETE"

rateLimit:
  windowMs: 900000
  max: 100

morganFormat: "none" # "none" | "dev" | "combined" | "common" | "short" | "tiny"

requireHTTPS: false

cookie:
  maxAge: 100000 # 100 seconds

# Service-specific configs
services:
  mailer:
    enabled: true
    config:
      senderAddress: "noreply@yourbusiness.com"
      templates:
        # Replaceable variables denoted by ${}
        newAuthToken:
          subject: "Purchase Confirmation"
          text: "Your purchase was successful. Here is your new auth token: ${AUTH_TOKEN}"
          html: "<p>Your purchase was successful. Here is your new auth token: <strong>${AUTH_TOKEN}</strong></p>"

  payment:
    enabled: true
    config:
      successRoute: "/payment-success"
      cancelRoute: "/"

  db:
    enabled: true
    config:
      sessionCollection: "sessions"
